# Generated by Django 3.2.5 on 2021-09-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('place', models.CharField(max_length=30)),
            ],
        ),
    ]
