# Generated by Django 3.2.5 on 2021-09-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_salary', models.IntegerField()),
            ],
        ),
    ]
