# Generated by Django 3.2.5 on 2021-09-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('mat_id', models.AutoField(primary_key=True, serialize=False)),
                ('mat_name', models.CharField(max_length=30)),
                ('mat_price', models.IntegerField()),
            ],
        ),
    ]
