# Generated by Django 3.2.5 on 2021-08-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPosts',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.TextField(max_length=50)),
                ('blog_content', models.TextField(max_length=500)),
                ('blog_author', models.CharField(max_length=50)),
                ('blog_date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
