# Generated by Django 3.2.5 on 2021-08-20 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_replie'),
    ]

    operations = [
        migrations.AddField(
            model_name='replie',
            name='posts',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.blogposts'),
        ),
    ]
