# Generated by Django 3.2.5 on 2021-08-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_replie_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replie',
            name='posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogposts'),
        ),
    ]
