# Generated by Django 3.2.5 on 2021-08-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_replie_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Replie',
        ),
    ]
