# Generated by Django 3.2.5 on 2021-08-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_replie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='comments',
            field=models.TextField(),
        ),
    ]
