# Generated by Django 3.2.5 on 2021-08-23 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogcomments_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogcomments'),
        ),
    ]
