# Generated by Django 3.2.5 on 2021-08-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoSite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='static/DemoSite/images')),
                ('gender', models.CharField(choices=[('Male', 'Make'), ('Female', 'Female')], max_length=10)),
            ],
        ),
    ]
