# Generated by Django 3.2.5 on 2021-08-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demosite',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
