# Generated by Django 3.2.5 on 2021-08-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoSite', '0003_demosite_hobbies'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
    ]
